#!/usr/bin/env node
/* build-palette.mjs — emit a perceptually uniform neutral scale in
 * helm-lab CSS syntax (helmlch). Runs through postcss-helmlab at build
 * time which compiles each helmlch() into:
 *   sRGB rgb() inline + P3 @supports + Rec2020 @supports.
 *
 * Why generate this rather than hand-author it: the lightness stops
 * (50 → 950) come from helmlab's GenSpace semantic-scale algorithm,
 * which spaces them on perceptually uniform steps tuned for design
 * tokens. We re-import the seed at build time so changing the seed
 * regenerates the whole scale consistently.
 *
 * Output: landing/_palette.css (helmlch CSS, NOT yet compiled to rgb).
 * That file is then run through PostCSS in build-site.mjs.
 */
import { Helmlab } from "helmlab";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// Mid-tone neutral seed; helmlab's semanticScale anchors here at level 500.
const SEED = "#737373";

const hl = new Helmlab({ neutralCorrection: true });
const scale = hl.semanticScale(SEED);

// Convert each scale entry to helmlch(L C h) values via helmlab's GenSpace.
// chroma will be ≈ 0 (pure neutrals), hue is irrelevant but we keep helmlab's
// computed value so postcss-helmlab can round-trip cleanly.
function toHelmlch(hex) {
  const lab = hl.genFromHex(hex);   // Gen Lab [L, a, b]
  const L = lab[0];
  const a = lab[1];
  const b = lab[2];
  const C = Math.sqrt(a * a + b * b);
  let h = (Math.atan2(b, a) * 180) / Math.PI;
  if (h < 0) h += 360;
  return `helmgenlch(${L.toFixed(4)} ${C.toFixed(5)} ${h.toFixed(2)}deg)`;
}

const lines = [
  "/* AUTO-GENERATED by tools/build-palette.mjs — do not edit by hand.",
  " * Re-run via `npm run build:palette` after changing the seed.",
  " *",
  ` * Seed: ${SEED}`,
  " * Pipeline:",
  " *   helmlab.semanticScale(seed) → 11 hex stops",
  " *   → helmgenlch(L C h) (CSS)",
  " *   → postcss-helmlab → rgb() inline + P3/@Rec2020 @supports overrides",
  " * https://helmlab.space//",
  " */",
  "",
  ":root {",
];

for (const [level, hex] of Object.entries(scale).sort((a, b) => Number(a[0]) - Number(b[0]))) {
  lines.push(`  --neutral-${level}: ${toHelmlch(hex)};`);
}

lines.push("}");
lines.push("");

const out = lines.join("\n") + "\n";
const outPath = resolve(ROOT, "landing/_palette.css");
writeFileSync(outPath, out);

console.log(`[build-palette] wrote ${outPath}`);
console.log(`  seed: ${SEED}`);
console.log(`  scale: ${Object.keys(scale).length} steps in helmgenlch syntax`);
