#!/usr/bin/env node
/* compile-acs.mjs — Build pipeline for ACS stylesheets.
 *
 * Reads one or more .acs files, parses them with the same parser the
 * runtime uses, then emits a JSON preset registry that production
 * runtimes can load without parsing CSS at startup.
 *
 * Usage:
 *   node tools/compile-acs.mjs poc/defaults.acs poc/showcase.acs > registry.json
 *   node tools/compile-acs.mjs --pretty poc/*.acs > registry.json
 *   node tools/compile-acs.mjs --bundle poc/*.acs > bundle.js
 *
 * Flags:
 *   --pretty     pretty-print the JSON output
 *   --bundle     emit a JS module: `export default {...}` instead of JSON
 *   --no-rules   only emit @sound + @sound-keyframes (skip selector rules)
 *   --out FILE   write to file instead of stdout
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parse, parseKeyframes } from "../poc/runtime/parse.js";

const args = process.argv.slice(2);
const flags = {
  pretty: false,
  bundle: false,
  rulesOnly: true,
  out: null,
  files: [],
};
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === "--pretty") flags.pretty = true;
  else if (a === "--bundle") flags.bundle = true;
  else if (a === "--no-rules") flags.rulesOnly = false;
  else if (a === "--out") flags.out = args[++i];
  else if (a.startsWith("--")) {
    console.error(`Unknown flag: ${a}`);
    process.exit(2);
  } else {
    flags.files.push(a);
  }
}
if (!flags.files.length) {
  console.error("Usage: compile-acs.mjs [--pretty|--bundle|--out FILE] <files...>");
  process.exit(1);
}

const sounds = {};
const keyframes = {};
const rules = [];

for (const file of flags.files) {
  const path = resolve(file);
  const text = readFileSync(path, "utf8");
  const parsed = parse(text);
  for (const r of parsed) {
    if (r.selector.startsWith("@sound-keyframes ")) {
      const name = r.selector.slice("@sound-keyframes ".length).trim();
      if (Array.isArray(r.decls.__sequence)) keyframes[name] = r.decls.__sequence;
    } else if (r.selector.startsWith("@sound ")) {
      const name = r.selector.slice("@sound ".length).trim();
      sounds[name] = r.decls;
    } else if (flags.rulesOnly !== false) {
      rules.push({
        selector: r.selector,
        decls: r.decls,
        ...(r.mediaCondition ? { mediaCondition: r.mediaCondition } : {}),
      });
    }
  }
}

const registry = {
  version: 1,
  generatedAt: new Date().toISOString(),
  sources: flags.files.map((f) => f.replace(/^.*\//, "")),
  sounds,
  keyframes,
  rules,
  counts: {
    sounds: Object.keys(sounds).length,
    keyframes: Object.keys(keyframes).length,
    rules: rules.length,
  },
};

const json = flags.pretty ? JSON.stringify(registry, null, 2) : JSON.stringify(registry);
const out = flags.bundle
  ? `// Generated by tools/compile-acs.mjs at ${registry.generatedAt}\nexport default ${json};\n`
  : json;

if (flags.out) {
  writeFileSync(flags.out, out);
  console.error(
    `[compile-acs] wrote ${flags.out} — ` +
    `${registry.counts.sounds} sounds, ${registry.counts.keyframes} keyframes, ` +
    `${registry.counts.rules} rules`
  );
} else {
  process.stdout.write(out);
}
